using System;
using System.Collections.Generic;

namespace CcMis.Models
{
    public partial class Register
    {
        public string SAccountNo { get; set; }
        public string SRoomType { get; set; }
        public string SRoomNo { get; set; }
        public string SDiscount { get; set; }
        public string DiscPerson { get; set; }
        public string NStandRate { get; set; }
        public string NFactRate { get; set; }
        public string NServe { get; set; }
        public string CServe { get; set; }
        public string DHotelDate { get; set; }
        public string DArriveDate { get; set; }
        public string DDepartDate { get; set; }
        public string SIsGroup { get; set; }
        public string SGroupNo { get; set; }
        public string VcName { get; set; }
        public string VeName1 { get; set; }
        public string VeName2 { get; set; }
        public string CSex { get; set; }
        public string DBirthday { get; set; }
        public string SCardType { get; set; }
        public string SIdCard { get; set; }
        public string SCountry { get; set; }
        public string SVisaType { get; set; }
        public string SVisaCard { get; set; }
        public string CIsTurn { get; set; }
        public string STurnAccnt { get; set; }
        public string CompAcct { get; set; }
        public string VcCompany { get; set; }
        public string VcAddress { get; set; }
        public string VcRemark { get; set; }
        public string Gtype { get; set; }
        public string StatiGtype { get; set; }
        public decimal? NCharge { get; set; }
        public decimal? NPay { get; set; }
        public decimal? NBalance { get; set; }
        public string DSetDate { get; set; }
        public string SSetWorkNo { get; set; }
        public string SCheckout { get; set; }
        public string SClass { get; set; }
        public string SPaymth { get; set; }
        public string SResvnum { get; set; }
        public int? NCount { get; set; }
        public string SSale { get; set; }
        public string SConnect { get; set; }
        public string SInGuest { get; set; }
        public string SLevel { get; set; }
        public string STax { get; set; }
        public decimal? NTax { get; set; }
        public string STaxEmp { get; set; }
        public string DOutDate { get; set; }
        public string SOutClass { get; set; }
        public string SOutEmp { get; set; }
        public string Saler { get; set; }
        public string OriType { get; set; }
        public string Authorize { get; set; }
        public string DelayCode { get; set; }
        public string DelayEmp { get; set; }
        public string Viplevel { get; set; }
        public string GtypeCode { get; set; }
        public string SecLevel { get; set; }
        public string GuestNote { get; set; }
        public string PriceCode { get; set; }
        public string GtosMss { get; set; }
        public string GtosMark { get; set; }
        public string TbRequest { get; set; }
        public string SCheckOut { get; set; }
        public string SYudinNo { get; set; }
        public string LateDate { get; set; }
        public string LateTime { get; set; }
        public int? LateDays { get; set; }
        public string OrgDate { get; set; }
        public string OSize { get; set; }
        public string FinDate { get; set; }
        public string StartDep { get; set; }
        public string AdCompany { get; set; }
        public string Vipcardid { get; set; }
        public decimal? DDaishou { get; set; }
        public decimal? DSaunaTotcharge { get; set; }
        public decimal? NSaunaChg { get; set; }
        public string RecordCode { get; set; }
        public string SDing { get; set; }
        public string SKeyno { get; set; }
        public string SSaunaAcct { get; set; }
        public string SSaunaKeyno { get; set; }
        public string SSaunaacct { get; set; }
        public string SSaunaend { get; set; }
        public string SUnionSauna { get; set; }
        public string SsLateSign { get; set; }
        public string VcTel { get; set; }
        public string VipCard { get; set; }
        public string VisaValidity { get; set; }
        public string SDepTime { get; set; }
        public string Breakfast { get; set; }
        public int? Daysin { get; set; }
        public string SeaportIn { get; set; }
        public string DArriveWorkdate { get; set; }
        public string DDepartWorkdate { get; set; }
        public string VipNo { get; set; }
        public string STele { get; set; }
        public string SFox { get; set; }
        public string SEmail { get; set; }
        public string VipCode { get; set; }
        public long? Marks { get; set; }
        public string Event { get; set; }
        public string RateCode { get; set; }
        public string SeaportDate { get; set; }
        public string CtDept { get; set; }
        public string Wq { get; set; }
        public string Pl { get; set; }
        public string Bar { get; set; }
        public string SSecret { get; set; }
        public decimal? Resvnid { get; set; }
        public string STogether { get; set; }
        public int? NGuest { get; set; }
        public DateTime? DCheckoutDate { get; set; }
    }
}
